<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title><![CDATA[Category: NoSQL | Jeff Beck]]></title>
  <link href="http://beckje01.github.io/blog/categories/nosql/atom.xml" rel="self"/>
  <link href="http://beckje01.github.io/"/>
  <updated>2014-07-01T21:52:55-05:00</updated>
  <id>http://beckje01.github.io/</id>
  <author>
    <name><![CDATA[Jeff Beck]]></name>
    <email><![CDATA[beckje01@gmail.com]]></email>
  </author>
  <generator uri="http://octopress.org/">Octopress</generator>

  
  <entry>
    <title type="html"><![CDATA[Cassandra Not Available After Starting]]></title>
    <link href="http://beckje01.github.io/blog/2012/12/28/cassandra-not-available-after-starting/"/>
    <updated>2012-12-28T04:25:45-06:00</updated>
    <id>http://beckje01.github.io/blog/2012/12/28/cassandra-not-available-after-starting</id>
    <content type="html"><![CDATA[<p>Iâ€™ve been working with the DataStax Enterprise 2.01 install for a bit now and it was working great until one day I was no longer able to get any queries to work using the cqlsh I was just getting the error that one or more nodes was unavailable. I tried restarting and still nothing would work I got a few errors in the logs (shown below).</p>

<p>I was able to quickly fix the error by removing my data directory and starting fresh as this is just my development environment that works great for me. You can find your data directory in the cassandra.yaml file ($DSE_HOME/resources/cassandra/conf/cassandra.yaml), look for the <em>data_file_directories</em> entry. Mine was set to <em>/var/lib/cassandra/data</em> so I just ran the following and started cassandra fresh and everything is back to working order.</p>

<p><code>sh
rm -r /var/lib/cassandra/data
</code></p>

<p>```</p>

<pre><code>INFO [JOB-TRACKER-INIT] 2012-12-28 10:32:32,515 JobTracker.java (line 2427) problem cleaning system directory: cfs:/tmp/hadoop-jeffbeck/mapred/system
java.io.IOException: UnavailableException()
    at com.datastax.bdp.hadoop.cfs.CassandraFileSystemThriftStore.listSubPaths(CassandraFileSystemThriftStore.java:1137)
    at com.datastax.bdp.hadoop.cfs.CassandraFileSystem.listStatus(CassandraFileSystem.java:192)
    at org.apache.hadoop.mapred.JobTracker.&lt;init&gt;(JobTracker.java:2392)
    at org.apache.hadoop.mapred.JobTracker.&lt;init&gt;(JobTracker.java:2195)
    at org.apache.hadoop.mapred.JobTracker.&lt;init&gt;(JobTracker.java:2189)
    at org.apache.hadoop.mapred.JobTracker.startTracker(JobTracker.java:303)
    at org.apache.hadoop.mapred.JobTracker.startTracker(JobTracker.java:294)
    at org.apache.hadoop.mapred.HadoopTrackerPlugin$1.run(HadoopTrackerPlugin.java:230)
    at java.lang.Thread.run(Thread.java:680)
Caused by: UnavailableException()
    at org.apache.cassandra.service.ReadCallback.assureSufficientLiveNodes(ReadCallback.java:212)
    at org.apache.cassandra.service.StorageProxy.scan(StorageProxy.java:1083)
    at org.apache.cassandra.thrift.CassandraServer.get_indexed_slices(CassandraServer.java:746)
    at com.datastax.bdp.hadoop.cfs.CassandraFileSystemThriftStore.listSubPaths(CassandraFileSystemThriftStore.java:1120)
    ... 8 more
</code></pre>

<p>```</p>
]]></content>
  </entry>
  
</feed>
